<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="2" hostname="JEDUn4" name="com.egtinteractive.chat.server.stresstests.RandomTests" tests="3" failures="0" timestamp="14 Jan 2019 07:41:56 GMT" time="0.007" errors="1">
  <testcase name="startTheServer" time="0.007" classname="com.egtinteractive.chat.server.stresstests.RandomTests">
    <error type="java.lang.RuntimeException" message="java.net.ConnectException: Connection refused (Connection refused)">
      <![CDATA[java.lang.RuntimeException: java.net.ConnectException: Connection refused (Connection refused)
at com.egtinteractive.chat.server.stresstests.RandomTests.setResources(RandomTests.java:84)
at com.egtinteractive.chat.server.stresstests.RandomTests.startTheServer(RandomTests.java:45)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
at org.testng.TestRunner.beforeRun(TestRunner.java:529)
at org.testng.TestRunner.run(TestRunner.java:497)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
at java.net.PlainSocketImpl.socketConnect(Native Method)
at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
at java.net.Socket.connect(Socket.java:589)
at java.net.Socket.connect(Socket.java:538)
at java.net.Socket.<init>(Socket.java:434)
at java.net.Socket.<init>(Socket.java:211)
at com.egtinteractive.chat.server.stresstests.RandomTests.setResources(RandomTests.java:77)
... 25 more
]]>
    </error>
  </testcase> <!-- startTheServer -->
  <testcase name="addRoom" time="0.000" classname="com.egtinteractive.chat.server.stresstests.RandomTests">
    <skipped/>
  </testcase> <!-- addRoom -->
  <testcase name="joinRoom" time="0.000" classname="com.egtinteractive.chat.server.stresstests.RandomTests">
    <skipped/>
  </testcase> <!-- joinRoom -->
</testsuite> <!-- com.egtinteractive.chat.server.stresstests.RandomTests -->
